audit_header: false
title: "Burbank's Best Real Estate Training - Brad Korb"
description: Brad Korb, a top Real Estate Agent in Burbank, shares his own internal real estate agent training for free. His Real Estate Training, Tips and Advice will help you sell more homes in less time.
show_custom_links: true
custom_links:
  - title: Join Our Team
    url: /join-our-team/
  - title: Events
    url: #
  - title: Free Strategy Call
    url: /strategy-call/
  - title: Free Newsletter
    url: /subscribe/
client:
  name: Brad Korb
  license_number: 'BRE # 00698730'
  about_markdown: |
    As one of the premier real estate businesses in the LA area, Brad Korb's real estate team is unmatched in their level of commitment and tireless devotion they provide to their clients. For over three decades, he has helped his clients visualize and obtain their goals of buying or selling a home. He sits down and listens to their unique needs and desires, then puts together the best strategies for achieving the results they want.  Having participated in every aspect of the real estate process over the years, he knows where to center his attention in order to bring about success.Brad surrounds himself with a team of professionals who each handle various tasks that need attention, giving him the freedom to focus directly on your transaction. With years of experience with buyers and sellers in the Burbank community, Brad is an unparalleled resource for everything from Burbank’s real estate market to community services.  So when your family is ready to move in the Glendale, Burbank , Sun Valley, North Hollywood and surrounding areas in the San Fernando Valley, contact the professional who is Focused on What Matters to You.
  market: Burbank
  brand: The Brad Korb Real Estate Group
  brokerage:
  address: 3813 W. Magnolia Blvd.<br>Burbank, CA 91505
  phone: 818-953-5300
  phone_type:
  phone2:
  phone2_type:
  email: brad@bradkorb.com
  url: https://www.bradkorb.com

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: "Looking to Build Your Real Estate Career?"
    CTA_text: "Let's talk about how The Brad Korb Real Estate Group can take your business to new heights."
    CTA_link_text: "Free Strategy Session"
    CTA_url: /contact/

# second_sidebar_CTA:
#   - CTA_image_path2: /img/cta-images/002.jpg
#     CTA_title2: "Join Our Team"
#     CTA_text2: "Sell more homes by joining forces with the our dynamic real estate company."
#     CTA_link_text2: "Career Info"
#     CTA_url2: /

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/TheBradKorbRealEstateGroup
  linkedin_url: http://www.linkedin.com/in/bradkorb/
  youtube_url: https://www.youtube.com/channel/UCiJwvniUev3k1C6rqTEvscQ
  twitter_url: https://twitter.com/bradkorb
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: 'Burbank Real Estate Podcast with Brad Korb'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the Burbank Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from The Brad Korb Real Estate Group - your professional Burbank Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in Burbank, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Brad Korb'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: Burbank Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#D2121D'
  theme_color: '#034275'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

navbar_colors:
  border_bottom:

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: transparent

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#D2121D'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
